### ISSUE TITLE
Paint bucket doesn't work on vertical half blocks

### ISSUE THREAD

**Issue by Kirkman** [andyherbert/ansiedit#3]
When I use the paint bucket on a big solid-color blob, it doesn't fill vertical half blocks of the same color.

**Comment by andyherbert** [comment]
That's strange, is there any chance you could provide a screenshot?

**Comment by andyherbert** [comment]
Actually, scratch that, I get what you mean now.

**Comment by andyherbert** [comment]
Let me know if this doesn't solve the issue.
