### ISSUE TITLE
Open file dialog...

### ISSUE THREAD

**Issue by drblackfox** [andyherbert/ansiedit#5]
Andy,

First off - this is one fantastic piece of software so far. Painting in it feels exactly like Photoshop for me, which is a huge bonus for my workflow.. current working on a game with ANSI art, and this will cut down on a lot of painting time vs. PabloDraw.

I'm running a local copy of AE on in OS X, and I've noticed that the File Open menu item has disappeared from the File Menu. It appears on your online demo, so am I missing something here?

(In fact, it seems that many File menu options are missing on my local copy)

Thanks!

**Comment by andyherbert** [comment]
It depends what you mean by 'local copy'. The files have to be hosted on a web server, fortunately there's an easy way to do this on OSX:

https://lifehacker.com/start-a-simple-web-server-from-any-directory-on-your-ma-496425450

**Comment by drblackfox** [comment]
Sorry, should have been more specific. I installed brew/npm/node, cloned a local copy of the most recent gh-pages branch, and I'm running server.js on localhost:3000. When I point Safari or Chrome (doesn't matter which browser), the File menu is missing items that appear in your online demo version of the program.

Did I grab the wrong release/fork by accident, or is there something wrong on my end? Screenshot attached.
![screen shot 2017-11-20 at 1 16 58 pm](https://user-images.githubusercontent.com/6203391/33039508-65f0fb74-cdf5-11e7-8d56-8e6a9359db03.png)

**Comment by andyherbert** [comment]
I see. In collaboration mode it disables certain menu items because it attempts to prevent large destructive changes from being made when multiple users are editing the same document. 

Comment-out lines 21-21 in server.js to prevent the websocket from being created, and it should start in the local document mode.

**Comment by drblackfox** [comment]
Commented out:
`app.ws("/", (ws, req) => {
    ws.send(ansiedit.getStart(req.sessionID));
    ws.send(ansiedit.getImageData().data, {"binary": true});
    ws.on("message", (msg) => {
        ansiedit.message(JSON.parse(msg), req.sessionID, wss.clients);
    });
    ws.on("close", () => {
        ansiedit.closeSession(req.sessionID, wss.clients);
    });
});`

and it threw an error (attached). Any insights? Am happy to debug this, but if you've got an idea off the top of your head..
![screen shot 2017-11-20 at 2 10 39 pm](https://user-images.githubusercontent.com/6203391/33041753-a4adc1f6-cdfc-11e7-8606-60ed0f19f7db.png)

**Comment by andyherbert** [comment]
Have you now tried reloading the page?

**Comment by drblackfox** [comment]
Yes :)

**Comment by drblackfox** [comment]
Absolutely baffled. Just re-downloaded the gh-pages branch, reinstalled from scratch, and now it's working just fine -- File menus and all. Sorry for wasting your time Andy.

**Comment by andyherbert** [comment]
It's alright.

**Comment by drblackfox** [comment]
Btw - any interest in a Safari-friendly fork of ansiedit? I just passed the scripts through Babel to translate to Safari-friendly js... works just great afterward.

**Comment by andyherbert** [comment]
In what way is it Safari friendly?

**Comment by drblackfox** [comment]
Safari 9.x won't load most of the scripts due to its incompatibility with arrow functions... it hangs with a bunch of 'unexpected token' errors in the js console.

**Comment by andyherbert** [comment]
Oh, I see. I'd rather have the arrow syntax for anonymous functions, to be honest.

**Comment by drblackfox** [comment]
Yeah, I get ya.. same here. Just had to transpile on my end because I run Safari for most of my dev work.
